basePath: /api
definitions:
  main.Match:
    description: API para gestión de partidos de fútbol
    properties:
      awayGoals:
        type: integer
      awayTeam:
        type: string
      extraTime:
        type: integer
      homeGoals:
        type: integer
      homeTeam:
        type: string
      id:
        type: integer
      matchDate:
        type: string
      redCards:
        type: integer
      yellowCards:
        type: integer
    required:
    - awayTeam
    - homeTeam
    - matchDate
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gestión de partidos de fútbol
  title: lab6-api
  version: "1.0"
paths:
  /api/matches:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Match'
            type: array
      summary: Listar todos los partidos
      tags:
      - Partidos
    post:
      consumes:
      - application/json
      parameters:
      - description: Datos del partido
        in: body
        name: match
        required: true
        schema:
          $ref: '#/definitions/main.Match'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Match'
      summary: Crear nuevo partido
      tags:
      - Partidos
  /api/matches/{id}:
    delete:
      parameters:
      - description: ID del partido
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Eliminar partido
      tags:
      - Partidos
    get:
      parameters:
      - description: ID del partido
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Match'
        "404":
          description: Not Found
          schema:
            type: object
      summary: Obtener un partido por ID
      tags:
      - Partidos
    put:
      consumes:
      - application/json
      parameters:
      - description: ID del partido
        in: path
        name: id
        required: true
        type: integer
      - description: Datos actualizados
        in: body
        name: match
        required: true
        schema:
          $ref: '#/definitions/main.Match'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Match'
      summary: Actualizar partido
      tags:
      - Partidos
  /api/matches/{id}/extratime:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID del partido
        in: path
        name: id
        required: true
        type: integer
      - default: 2
        description: Minutos de tiempo extra
        in: query
        name: minutes
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Match'
      summary: Registrar tiempo extra
      tags:
      - Estadísticas
  /api/matches/{id}/goals:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID del partido
        in: path
        name: id
        required: true
        type: integer
      - description: Goles del equipo local
        in: query
        name: homeGoals
        type: integer
      - description: Goles del equipo visitante
        in: query
        name: awayGoals
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Match'
      summary: Actualizar goles del partido
      tags:
      - Estadísticas
  /api/matches/{id}/redcards:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID del partido
        in: path
        name: id
        required: true
        type: integer
      - default: 1
        description: Cantidad de tarjetas a añadir
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Match'
      summary: Registrar tarjeta roja
      tags:
      - Estadísticas
  /api/matches/{id}/yellowcards:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID del partido
        in: path
        name: id
        required: true
        type: integer
      - default: 1
        description: Cantidad de tarjetas a añadir
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Match'
      summary: Registrar tarjeta amarilla
      tags:
      - Estadísticas
swagger: "2.0"
